name:                cspim
version:             0.1.0.0
github:              "JKTKops/cspim"
license:             BSD3
author:              "Max Kopinsky"
maintainer:          "zerglingk9012@gmail.com"
copyright:           "2019 Max Kopinsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JKTKops/cspim#readme>

default-extensions:
- ApplicativeDo

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:           src/
  dependencies:
  - array
  - containers
  - filepath
  - hoopl
  - lens
  - mtl
  - monad-validate
  - parsec
  - pretty
  - template-haskell
  - haskell-src-meta

executables:
  cspim:
    main:                Main.hs
    source-dirs:         app/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - cspim
    - cmdargs

tests:
  cspim-test:
    main:                Spec.hs
    source-dirs:         test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cspim
